### ISSUE TITLE
Validation for pageSize for list actions and PagerFanta [500 Error]

### ISSUE THREAD

**Issue by amustaine** [RuSS-B/tiny-rest#12]
Current validation allows negative values for the `pageSize` query param - https://github.com/RuSS-B/tiny-rest/blob/master/src/TransferObject/PaginationTrait.php#L20

But it is not allowed by PagerFanta in `PagerFanta::checkMaxPerPage()`

```
if ($maxPerPage < 1) { 
   throw new LessThan1MaxPerPageException(); 
}
```

And I have a 500 error

**Comment by RuSS-B** [comment]
Great catch @amustaine! Working on it now

**Comment by RuSS-B** [comment]
Fixed! The negative pageSize will throw a validation exception by now
